In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [ ]:
# 1. Create two rank-2 tensors of ones and zeros with 3 rows and columns each, and carry out the arithmetic operations 
#    of addtion, subtraction and multiplication.

In [ ]:
x = tf.ones([3,3])
x.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
y = tf.zeros([3,3])
y.numpy()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [ ]:
print(tf.add(x,y))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
print(tf.subtract(x,y))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
print(tf.subtract(y,x))

tf.Tensor(
[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]], shape=(3, 3), dtype=float32)


In [ ]:
print(tf.multiply(x,y))

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
#####################################################################################

In [ ]:
# 2. Suppose you created a rank-3 tf array as follows:
#    array([[[ 6,  2,  4],
#            [12,  8, 10]],

#           [[ 5,  1,  3],
#            [11,  7,  9]],

#          [[21, 32, 54],
#           [13, 49, 36]]], dtype=int32)

#    How to access the following from the above tensor? 
#    array([[[ 2,  4],
#            [ 8, 10]],

#           [[ 1,  3],
#            [ 7,  9]]], dtype=int32)


In [ ]:
tv = tf.Variable([[[6,2,4],[12,8,10]],[[5,1,3,],[11,7,9]],[[21,32,54],[13,49,36]]])
tv.numpy()

array([[[ 6,  2,  4],
        [12,  8, 10]],

       [[ 5,  1,  3],
        [11,  7,  9]],

       [[21, 32, 54],
        [13, 49, 36]]], dtype=int32)

In [ ]:
tv[0:2,:,1:3].numpy()

array([[[ 2,  4],
        [ 8, 10]],

       [[ 1,  3],
        [ 7,  9]]], dtype=int32)

In [ ]:
##################################################################################################

In [ ]:
# 3. How will you generate the following output?
#    array([[ 76, 100],
#           [166, 226]], dtype=int32)

In [ ]:
a = tf.constant([2,4,6,8,10,12], shape=[2,3])
b = tf.constant([1,3,5,7,9,11], shape=[3,2])

In [ ]:
print(a)

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
print(b)

tf.Tensor(
[[ 1  3]
 [ 5  7]
 [ 9 11]], shape=(3, 2), dtype=int32)


In [ ]:
c = tf.matmul(a,b)
c.numpy()

array([[ 76, 100],
       [166, 226]], dtype=int32)

In [ ]:
#####################################################################################################

In [ ]:
# 4. Write a code snippet to create a tensor as follows. Also display the rank of the tensor created.
#    array([[[ 7,  14,  21],
#            [35,  45, 95]],

#           [[33,  111,  23],
#            [22,  48,  64]],dtype=int32)
 

In [ ]:
tv1 = tf.constant([[[7,14,21],[35,45,95]],[[33,111,23,],[22,48,64]]])
tv1.numpy()

array([[[  7,  14,  21],
        [ 35,  45,  95]],

       [[ 33, 111,  23],
        [ 22,  48,  64]]], dtype=int32)

In [ ]:
tf.rank(tv1).numpy()

3

In [ ]:
##########################################################################################################