In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [7]:
# 1. Write a pice of code to generate the following output:
#    array([[0.,0.],
#           [1.,1.]], dtype=float32)

In [3]:
c1 = tf.zeros([1,2])
c1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0., 0.]], dtype=float32)>

In [4]:
c2 = tf.ones([1,2])
c1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0., 0.]], dtype=float32)>

In [6]:
c3 = tf.concat([c1,c2],0)
c3.numpy()

array([[0., 0.],
       [1., 1.]], dtype=float32)

In [8]:
#############################################################################################

In [9]:
# 2. What is the code snippet for creating  a rank-3 tensor of ones with 3 rows and 2 columns?

In [11]:
c4 = tf.ones([3,3,2])
c4.numpy()

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)

In [12]:
print(c4)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(3, 3, 2), dtype=float32)


In [13]:
###############################################################################################

In [16]:
# 3. How will you generate the following output? Create a code snippet for the same.
#    array([[22,34],
#           [46,74]], dtype=int32)

In [14]:
a = tf.constant([2,4,6,8], shape=[2,2])
b = tf.constant([1,3,5,7], shape=[2,2])

In [15]:
c = tf.matmul(a,b)
c.numpy()

array([[22, 34],
       [46, 74]], dtype=int32)

In [17]:
######################################################################################################

In [22]:
# 4. Suppose you created a rank-3 tf array as follows:
#    array([[[ 2,  4,  6],
#            [ 8, 10, 12]],

#            [[ 1,  3,  5],
#             [ 7,  9, 11]]], dtype=int32)
#    How to access the "array([ 5, 11], dtype=int32)" from the above tensor? Also, extract the value 5 alone from the tensor.

In [18]:
tv = tf.Variable([[[2,4,6],[8,10,12]],[[1,3,5,],[7,9,11]]])
tv.numpy()

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 1,  3,  5],
        [ 7,  9, 11]]], dtype=int32)

In [19]:
tv[1,:2,-1].numpy()

array([ 5, 11], dtype=int32)

In [20]:
tv[1,:,-1].numpy()

array([ 5, 11], dtype=int32)

In [21]:
tv[1,:1,-1].numpy()

array([5], dtype=int32)

In [23]:
########################################################################################